services:
    app_ia:
        build: ia
        mem_limit: 512m
        ports:
            - "8080:8080"
        environment:
            API_KEY: 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
            BASE_URL: https://api.groq.com/openai
        restart: always