spring.application.name=app_ia
groq.api.key=${API_KEY}
groq.api.base-url=${BASE_URL:https://api.groq.com/openai}
server.port=${PORT:8080}
spring.main.lazy-initialization=true
spring.threads.virtual.enabled=true
spring.cache.type=redis
spring.data.redis.url=${REDIS_URL:redis://localhost:6379}
server.error.whitelabel.enabled=false
server.forward-headers-strategy=framework
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax