spring.application.name=app_ia
spring.ai.openai.api-key=${API_KEY}
spring.ai.openai.base-url=${BASE_URL}
spring.ai.openai.chat.options.model=llama3-70b-8192
spring.ai.openai.temperature=0.7
server.port=${PORT:8080}
spring.main.lazy-initialization=true
spring.threads.virtual.enabled=true
